
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: copy files with SSH
      uses: easingthe/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        SOURCE: "./"
        REMOTE_HOST:  "ec2-3-90-213-82.compute-1.amazonaws.com"
        REMOTE_ USER: "ec2-user"
        TARGET: "/home/ec2-user"
       #https://www.youtube.com/watch?v=i8aRDekvyS0