name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  config-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Configurando JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Executando testes
        run: mvn test

  allure-report:
    steps:
    - name: Gerando Allure Report
      run: allure generate -c reports/allure-results -o reports/allure-results-html

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/home/ec2-user"
        EXCLUDE: ".git, .gitignore, .vscode, target/"
       #FONTE: https://www.youtube.com/watch?v=i8aRDekvyS0