name: TestAction
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Run a one-line script
        run: echo Hello world!

  deploy-dev:
    runs-on: ubuntu-20.04
    environment:
      name: dev
      url: 'http://www.omdbapi.com/'
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Configurando JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Executando testes
        run: mvn test
        #run: mvn -B package --file pom.xml
      
  deploy-hom:
    runs-on: ubuntu-20.04
    environment:
      name: hom
      url: 'http://www.omdbapi.com/'
    needs: deploy-dev
    steps:
    - name: Run a one-line script
      run: echo Deploy hom
      
  deploy-prod:
    runs-on: ubuntu-20.04
    environment:
      name: prod
      url: 'http://www.omdbapi.com/'
    needs: deploy-hom
    steps:
    - name: Run a one-line script
      run: echo Deploy prod
