name: Running Tests
on:
  push:
    workflow_dispatch:

jobs:
  config-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Configurando JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Executando testes
        run: mvn test
      